# Autogenerated wrapper script for peppi_jlrs_jll for aarch64-apple-darwin-julia_version+1.11.0
export libpeppi_jlrs

using Libiconv_jll
using Zstd_jll
JLLWrappers.@generate_wrapper_header("peppi_jlrs")
JLLWrappers.@declare_library_product(libpeppi_jlrs, "@rpath/libpeppi_jlrs.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Libiconv_jll, Zstd_jll)
    JLLWrappers.@init_library_product(
        libpeppi_jlrs,
        "lib/libpeppi_jlrs.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
