# Autogenerated wrapper script for peppi_jlrs_jll for x86_64-linux-gnu-julia_version+1.11.0
export libpeppi_jlrs

using Zstd_jll
JLLWrappers.@generate_wrapper_header("peppi_jlrs")
JLLWrappers.@declare_library_product(libpeppi_jlrs, "libpeppi_jlrs.so")
function __init__()
    JLLWrappers.@generate_init_header(Zstd_jll)
    JLLWrappers.@init_library_product(
        libpeppi_jlrs,
        "lib/libpeppi_jlrs.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
