# Autogenerated wrapper script for peppi_jlrs_jll for x86_64-w64-mingw32-julia_version+1.10.0
export libpeppi_jlrs

using Zstd_jll
JLLWrappers.@generate_wrapper_header("peppi_jlrs")
JLLWrappers.@declare_library_product(libpeppi_jlrs, "libpeppi_jlrs.dll")
function __init__()
    JLLWrappers.@generate_init_header(Zstd_jll)
    JLLWrappers.@init_library_product(
        libpeppi_jlrs,
        "bin\\libpeppi_jlrs.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
